package com.hugodev.otakuhub.core.ui.theme

import androidx.compose.ui.graphics.Color

// ==================== MODO CLARO - TEMA ANIME ====================
// Color primario: Rosa/Magenta brillante (estilo anime)
val primaryLight = Color(0xFFEE1D63)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFB3D9)
val onPrimaryContainerLight = Color(0xFF880E3E)

// Color secundario: Azul cian vibrante (complementa el tema)
val secondaryLight = Color(0xFF0097A7)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB3E5FC)
val onSecondaryContainerLight = Color(0xFF004D63)

// Color terciario: Naranja/Dorado (acentos anime)
val tertiaryLight = Color(0xFFFFA500)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD699)
val onTertiaryContainerLight = Color(0xFF664D00)

val errorLight = Color(0xFFD32F2F)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFCDD2)
val onErrorContainerLight = Color(0xFF7C0000)

// Fondos claros
val backgroundLight = Color(0xFFFCFCFC)
val onBackgroundLight = Color(0xFF1A1A1A)
val surfaceLight = Color(0xFFFCFCFC)
val onSurfaceLight = Color(0xFF1A1A1A)
val surfaceVariantLight = Color(0xFFEFD1DC)
val onSurfaceVariantLight = Color(0xFF4A3945)
val outlineLight = Color(0xFF7A6A74)
val outlineVariantLight = Color(0xFFD0B7C1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF302E31)
val inverseOnSurfaceLight = Color(0xFFF7F0F2)
val inversePrimaryLight = Color(0xFFFF80AB)
val surfaceDimLight = Color(0xFFDDD7DC)
val surfaceBrightLight = Color(0xFFFCFCFC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F0F4)
val surfaceContainerLight = Color(0xFFF0EAEE)
val surfaceContainerHighLight = Color(0xFFEAE4E9)
val surfaceContainerHighestLight = Color(0xFFE4DEE3)

// Contraste Medio - Modo Claro
val primaryLightMediumContrast = Color(0xFFB90C48)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFEE1D63)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF006B78)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF0097A7)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFFCC8400)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFFFA500)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFFB01C0E)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFD32F2F)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFCFCFC)
val onBackgroundLightMediumContrast = Color(0xFF1A1A1A)
val surfaceLightMediumContrast = Color(0xFFFCFCFC)
val onSurfaceLightMediumContrast = Color(0xFF0E0E10)
val surfaceVariantLightMediumContrast = Color(0xFFEFD1DC)
val onSurfaceVariantLightMediumContrast = Color(0xFF3C323B)
val outlineLightMediumContrast = Color(0xFF584E57)
val outlineVariantLightMediumContrast = Color(0xFF75636D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF302E31)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF7F0F2)
val inversePrimaryLightMediumContrast = Color(0xFFFF80AB)
val surfaceDimLightMediumContrast = Color(0xFFC9C2C7)
val surfaceBrightLightMediumContrast = Color(0xFFFCFCFC)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F0F4)
val surfaceContainerLightMediumContrast = Color(0xFFEAE4E9)
val surfaceContainerHighLightMediumContrast = Color(0xFFDED8DD)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD3CCD1)

// Alto Contraste - Modo Claro
val primaryLightHighContrast = Color(0xFF6D0032)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFFB90C48)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF003B48)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF00647C)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF663200)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFFCC8400)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF8B0000)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFFD32F2F)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFCFCFC)
val onBackgroundLightHighContrast = Color(0xFF1A1A1A)
val surfaceLightHighContrast = Color(0xFFFCFCFC)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEFD1DC)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF3C323B)
val outlineVariantLightHighContrast = Color(0xFF584E57)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF302E31)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFF80AB)
val surfaceDimLightHighContrast = Color(0xFFCCC6CB)
val surfaceBrightLightHighContrast = Color(0xFFFCFCFC)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3EDEF)
val surfaceContainerLightHighContrast = Color(0xFFE4DEE3)
val surfaceContainerHighLightHighContrast = Color(0xFFD8D2D7)
val surfaceContainerHighestLightHighContrast = Color(0xFFCCC6CB)

// ==================== MODO OSCURO - TEMA ANIME ====================
// Color primario: Rosa/Magenta claro (para fondo oscuro)
val primaryDark = Color(0xFFFF80AB)
val onPrimaryDark = Color(0xFF5D0033)
val primaryContainerDark = Color(0xFFB90C48)
val onPrimaryContainerDark = Color(0xFFFFD9E3)

// Color secundario: Cian claro
val secondaryDark = Color(0xFF80DEEA)
val onSecondaryDark = Color(0xFF003E47)
val secondaryContainerDark = Color(0xFF004D63)
val onSecondaryContainerDark = Color(0xFFB3E5FC)

// Color terciario: Naranja claro
val tertiaryDark = Color(0xFFFFD280)
val onTertiaryDark = Color(0xFF331600)
val tertiaryContainerDark = Color(0xFF664D00)
val onTertiaryContainerDark = Color(0xFFFFD699)

val errorDark = Color(0xFFEF5350)
val onErrorDark = Color(0xFF5F0000)
val errorContainerDark = Color(0xFFB01C0E)
val onErrorContainerDark = Color(0xFFFFCDD2)

// Fondos oscuros
val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFE8E8E8)
val surfaceDark = Color(0xFF121212)
val onSurfaceDark = Color(0xFFE8E8E8)
val surfaceVariantDark = Color(0xFF4A3945)
val onSurfaceVariantDark = Color(0xFFD0B7C1)
val outlineDark = Color(0xFF9A8A94)
val outlineVariantDark = Color(0xFF4A3945)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8E8E8)
val inverseOnSurfaceDark = Color(0xFF302E31)
val inversePrimaryDark = Color(0xFFEE1D63)
val surfaceDimDark = Color(0xFF0F0F0F)
val surfaceBrightDark = Color(0xFF3B3B3F)
val surfaceContainerLowestDark = Color(0xFF0A0A0A)
val surfaceContainerLowDark = Color(0xFF1A1A1E)
val surfaceContainerDark = Color(0xFF1E1E23)
val surfaceContainerHighDark = Color(0xFF28282D)
val surfaceContainerHighestDark = Color(0xFF333338)

// Contraste Medio - Modo Oscuro
val primaryDarkMediumContrast = Color(0xFFFF99C1)
val onPrimaryDarkMediumContrast = Color(0xFF3A001F)
val primaryContainerDarkMediumContrast = Color(0xFFCC1A52)
val onPrimaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
val secondaryDarkMediumContrast = Color(0xFF99E9F2)
val onSecondaryDarkMediumContrast = Color(0xFF00262E)
val secondaryContainerDarkMediumContrast = Color(0xFF0080A0)
val onSecondaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
val tertiaryDarkMediumContrast = Color(0xFFFFE0A6)
val onTertiaryDarkMediumContrast = Color(0xFF1F0D00)
val tertiaryContainerDarkMediumContrast = Color(0xFFD99200)
val onTertiaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
val errorDarkMediumContrast = Color(0xFFFB9393)
val onErrorDarkMediumContrast = Color(0xFF370000)
val errorContainerDarkMediumContrast = Color(0xFFC41C00)
val onErrorContainerDarkMediumContrast = Color(0xFFFFFFFF)
val backgroundDarkMediumContrast = Color(0xFF121212)
val onBackgroundDarkMediumContrast = Color(0xFFE8E8E8)
val surfaceDarkMediumContrast = Color(0xFF121212)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4A3945)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE3C8D7)
val outlineDarkMediumContrast = Color(0xFFB19BA5)
val outlineVariantDarkMediumContrast = Color(0xFF9A8A94)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE8E8E8)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF26262A)
val inversePrimaryDarkMediumContrast = Color(0xFFCC1A52)
val surfaceDimDarkMediumContrast = Color(0xFF0F0F0F)
val surfaceBrightDarkMediumContrast = Color(0xFF47474E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1B1F)
val surfaceContainerDarkMediumContrast = Color(0xFF25252B)
val surfaceContainerHighDarkMediumContrast = Color(0xFF303035)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B3B40)

// Alto Contraste - Modo Oscuro
val primaryDarkHighContrast = Color(0xFFFFECF3)
val onPrimaryDarkHighContrast = Color(0xFF30001A)
val primaryContainerDarkHighContrast = Color(0xFFFF80AB)
val onPrimaryContainerDarkHighContrast = Color(0xFF1A0018)
val secondaryDarkHighContrast = Color(0xFFE0F9FF)
val onSecondaryDarkHighContrast = Color(0xFF001820)
val secondaryContainerDarkHighContrast = Color(0xFF80DEEA)
val onSecondaryContainerDarkHighContrast = Color(0xFF000D12)
val tertiaryDarkHighContrast = Color(0xFFFFF1DC)
val onTertiaryDarkHighContrast = Color(0xFF150600)
val tertiaryContainerDarkHighContrast = Color(0xFFFFD280)
val onTertiaryContainerDarkHighContrast = Color(0xFF0D0400)
val errorDarkHighContrast = Color(0xFFFFECEB)
val onErrorDarkHighContrast = Color(0xFF230000)
val errorContainerDarkHighContrast = Color(0xFFEF5350)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF121212)
val onBackgroundDarkHighContrast = Color(0xFFE8E8E8)
val surfaceDarkHighContrast = Color(0xFF121212)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4A3945)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE3C8D7)
val outlineVariantDarkHighContrast = Color(0xFFE3C8D7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE8E8E8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF7D0033)
val surfaceDimDarkHighContrast = Color(0xFF121212)
val surfaceBrightDarkHighContrast = Color(0xFF565660)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1E1E23)
val surfaceContainerDarkHighContrast = Color(0xFF2E2E34)
val surfaceContainerHighDarkHighContrast = Color(0xFF393941)
val surfaceContainerHighestDarkHighContrast = Color(0xFF44444D)







